src/exceptions/config_error.py

- correct change set with just one file modification

989: Skip tests - addition

---

config/template_config.yaml
src/RecoExplorer.py
src/model/opensearch/base_data_accessor_opensearch.py
src/model/sagemaker/clustering_model_client.py

- fixed searching by url for mediathek

fixed searching by url in mediathek

---

config/template_config.yaml
src/controller/reco_controller.py
src/model/opensearch/base_data_accessor_opensearch.py
src/model/sagemaker/clustering_model_client.py

- fix with filtering by thematic category
- better logging

Reintegrating dev into main

---

.github/workflows/test.yml

Added github actions setup for unit test stage
- Runs on all push events independent of branch
- Runs on pull request to `dev` and `main`

SNTWREC-43: Add test stage in CICD setup

---

README.md
docker-compose.yaml
microservices/embeddingservice/config/config.yaml
microservices/embeddingservice/requirements.txt
microservices/ingestservice/config/config.yaml
microservices/ingestservice/src/main.py
microservices/searchservice/config/config.yaml
microservices/searchservice/src/oss_accessor.py

In this change I
- added a docker compose file to run microservices and opensearch locally
- fixed a few small issues in the microservices to make the services actually runable with docker compose

SNTWREC-51: Dockercompose für lokale Entwicklung

---

src/model/rest/nn_seeker_paservice.py
test/integration/test_controller_integrations.py

- added aditional parametrisation to pa service handler

Changes to PA Service REST handler

---

.github/workflows/build-publish-deploy.yml
.github/workflows/main.yml
.github/workflows/ms-embedding.yml
.github/workflows/ms-ingest.yml
.github/workflows/ms-search.yml
microservices/embeddingservice/src/main.py
microservices/ingestservice/src/main.py
microservices/searchservice/src/main.py

- add CICD for backend services

SNTWREC-27: Set up CICD for backend microservices

---

src/dto/wdr_content_item.py
src/util/dto_utils.py
src/view/cards/wdr/wdr_content_card.py
src/view/cards/wdr/wdr_content_reco_card.py
src/view/cards/wdr/wdr_content_start_card.py

For Testing replace content_type in c2c models: 
content_type: 'WDRContentItemDto'
and in OSS config change field mapping and primary_field:
field_mapping:
"created": "availableFrom"
"crid": "externalid"
primary_field: "externalId"

SNTWREC-115 add new WDR Content Item DTO and Cards for Frontend to map Sophora Meta Data from OSS

---

README.md
config/schema/ui_schema.json
src/view/RecoExplorerApp.py
src/view/ui_constants.py
src/view/widgets/text_area_input_widget.py

In UI Config can be tested like this: 
-   type: 'text_area_input'
label: 'Text'
url_parameter: 'text'

SNTWREC-86 add text area input widget to configuration based widgets

---

README.md
requirements.txt
src/controller/reco_controller.py
src/dto/item.py
src/model/nn_seeker.py
src/model/opensearch/nn_seeker_opensearch.py
src/view/ui_constants.py
src/view/widgets/slider_widget.py
test/unit/model/opensearch/test_nn_seeker_opensearch.py

In diesem Pull Request habe ich:
- die OpenSearchQuery Builder Logik vom Controller in den NnSeekerOpensearch geschoben und leicht refactored
- Tests für die Query Baulogik geschrieben
- einen neuen Filtertyp: "relativerange_filter" implementiert
- den Slider mit wireing versehen

SNTWREC-113: MaxDurationFilter für OpenSearch implementieren

---

README.md
config/schema/ui_schema.json
src/model/paservice/base_data_accessor_pa_service.py
src/view/ui_constants.py
src/view/widgets/slider_widget.py

Dieser Merge Request ist abgebranched von SNTWREC-112. Entsprechend sind hier noch Änderungen davon dabei.
zum testen dieses Element zu den blocks von der config_pa hinzufügen:
```
-   label: Längenfilter
components:
-   type: slider
name: Länge
start: 0.0
end: 10.0
step: 0.1
unit: x
label: relativerangefilter_duration
component_group: item_filter
```

SNTWREC-118: MaxDurationFilter für PA-Service implementieren

---

README.md
config/schema/ui_schema.json
src/view/RecoExplorerApp.py
src/view/ui_constants.py
src/view/widgets/accordion_widget.py
src/view/widgets/date_time_picker_widget.py
src/view/widgets/multi_select_widget.py
src/view/widgets/reset_button.py
src/view/widgets/slider_widget.py
src/view/widgets/text_area_input_widget.py
src/view/widgets/text_field_widget.py

Reset Buttons werden automatisch gerendered (wenn nicht aktiv deaktiviert) pro Block und passen sich an den jeweiligen Block an.

SNTWREC-92 add automatically rendered reset buttons for blocks

---

maintenance/Dockerfile.osscleanup
maintenance/Dockerfile.ossindex
maintenance/create_oss_index.py
microservices/embeddingservice/docker/Dockerfile
microservices/ingestservice/docker/Dockerfile
microservices/searchservice/docker/Dockerfile
src/RecoExplorer.py
src/controller/reco_controller.py
src/model/rest/nn_seeker_paservice.py
src/model/rest/nn_seeker_paservice_show.py
src/model/sagemaker/collab_model_client.py
src/model/u2c_seeker.py
src/view/RecoExplorerApp.py

- add filtering & postprocessing block to U2C section
- add user selection pass to pa service handler
- add new field `editorialCategories` to OSS indexing script
- fix pip reference in microservices Dockerfiles

SNTW-1193: Editorial Categories (U2C filtering)

---

src/RecoExplorer.py
src/util/file_utils.py
src/view/RecoExplorerApp.py

SNTWREC-145 display version information in sidebar when version-information.yaml is in config directory

SNTWREC-145 display version information

---

src/view/widgets/radio_box_widget.py

SNTWREC-174 fix visibility bug in radio box widget when widget like textbox is in a row with a tooltip

SNTWREC-174 fix visibility bug in radio box widget

---

src/view/widgets/reset_button.py

fix reset button functionality by checking for content of a row when collecting leaf widgets

SNTWREC-174 fix reset button functionality

---

src/controller/reco_controller.py
src/model/opensearch/base_data_accessor_opensearch.py
src/model/opensearch/nn_seeker_opensearch.py
src/model/rest/nn_seeker_paservice.py
src/view/cards/user_card.py

- unify reading of model parameters from config file
- unify way items are retrieved from opensearch

Sntw 1370 c2c ab mt

---

src/model/opensearch/base_data_accessor_opensearch.py

https://github.com/WestdeutscherRundfunkKoeln/recommender-explorer-config/pull/44

SNTWREC-234: Suchen per Sophora-ID im WDR-Mandanten ermöglichen

---

.github/workflows/build-publish-deploy.yml

SNTWREC-233 introduce matrix strategy for building microservices on two stages (prod-wdr and prod atmt)

SNTWREC-233 introduce matrix strategy for building microservices

---

src/view/RecoExplorerApp.py

SNTWREC-286-Amend-"Mandant wählen" -Widget in RecoExplorer

SNTWREC-286-Amend-"Mandant wählen" -Widget in RecoExplorer

---

src/view/cards/wdr/wdr_content_card.py
src/view/cards/wdr/wdr_content_reco_card.py
src/view/cards/wdr/wdr_content_start_card.py
src/view/widgets/reset_button.py

Hi @t-moster ,
I am creating this Pull request so that you can take a look into the changes.
Thank you,
Nerisa

Sntwrec 294 generate item detail overlay of re wdr content cards

---

.github/workflows/build-publish-deploy.yml

- updating the task definition package in the same way as was done in SNTWREC-325

updating task definition package

---

microservices/embeddingservice/config/config.yaml
microservices/embeddingservice/docker/Dockerfile
microservices/embeddingservice/src/constants.py
microservices/embeddingservice/src/embed_text.py
microservices/embeddingservice/src/main.py
microservices/embeddingservice/src/model_config_utils.py
microservices/embeddingservice/tests/config.yaml
microservices/embeddingservice/tests/test_api.py
microservices/embeddingservice/tests/test_util.py
requirements.txt

Models need to be passed by (for example by docker compose for testing) like: 
`MODELS: |
{
"wdr": {
"c2c_models": {
"Jina-A": {
"display_name": "Jina-A",
"handler": "NnSeekerOpenSearch@model.opensearch.nn_seeker_opensearch",
"endpoint": "opensearch://jina-embeddings-v2-base-de-4096",
"start_color": "#BB6859",
"reco_color": "#F78D7D",
"content_type": "WDRContentItemDto",
"default": true,
"model_name": "jina-embeddings-v2-base-de-4096",
"model_path": "sentence_transformers/jina-embeddings-v2-base-de-4096",
"display_in_reco_explorer": true
},
"Jina-B": {
"display_name": "Jina-B",
"handler": "NnSeekerOpenSearch@model.opensearch.nn_seeker_opensearch",
"endpoint": "opensearch://jina-embeddings-v2-base-de-128",
"start_color": "#BB6859",
"reco_color": "#F78D7D",
"content_type": …

SNTWREC-97 update model config to get passed as a env variable and mdify endpoints to return full model configs

---

README.md
src/controller/reco_controller.py
src/model/opensearch/base_data_accessor_opensearch.py
src/model/rest/nn_seeker_paservice.py
src/model/rest/nn_seeker_paservice_news.py
src/model/rest/nn_seeker_paservice_show.py
src/model/rest/nn_seeker_rest.py
src/view/RecoExplorerApp.py
src/view/ui_constants.py
src/view/widgets/refinement_widget.py
src/view/widgets/reset_button.py
test/unit/model/paservice/test_nn_seeker_pa_service.py
test/unit/model/paservice/test_nn_seeker_pa_service_news.py
test/unit/view/widgets/test_refinement_widget.py

* New widget introduced with fixed parameters
* Requests have been modified

SNTWREC-327-Refinement-Widget

---

config/schema/ui_schema.json

Due to the error raised while merging the Refinement ticket in the config repo I had to create a separate branch to handle this issue.
please take a look at the error in reco-config pipeline to make sure that the solution I suggested is valid

Schema fix for Refinement widget

---

src/controller/reco_controller.py

A bug fix regarding the WDR  tenant which was affected by the recent merge of the refinement widget.

wdr tentant fix
